### PR TITLE
fix: replace calculations with calculate utils currency method

### PR DESCRIPTION
**Pull request by brunovjk**
This pull request directly addresses issue #280 
Replaced erp component / modules , invoice , quote , payment calculations with calculate utils currency method

### CODE REVIEW

**Review by Deivids1234 — APPROVED** [review]

**Review by salahlalami — APPROVED** [review]

**Review by Ando22 — APPROVED** [review]

**Comment by Ando22** [comment]
@brunovjk please fix the conflict 🙏

**Comment by brunovjk** [comment]
How strange @Ando22 , I can't find the conflicts on my local.

**Comment by brunovjk** [comment]
> How strange @Ando22 , I can't find the conflicts on my local.

maybe redo the branch and pull request?

**Comment by polymahh** [comment]
@brunovjk did you run git pull origin dev  to update ur branch from dev?

**Comment by Ando22** [comment]
@brunovjk yess i still see the conflict in this PR

**Comment by brunovjk** [comment]
> @brunovjk yess i still see the conflict in this PR

Ok, let me fix here

**Comment by brunovjk** [comment]
> @brunovjk yess i still see the conflict in this PR

I believe I fixed it, can you check the changed files again please? Thanks.

**Pull request merged**
