### PR TITLE
Add Items list validation on `ReadItem` ERP Panel

### PR DESCRIPTION
**Pull request by Ando22**
## Overview
This pull request addresses the #334 Issue. on ERP Panel `ReadItem` feature. there's an iteration of `itemslist` in the front end. In the `PaymetInvoice` case, the data that the backend returns does not have an item object on the response. to prevent this similar case, I put conditional rendering to check if there's a list that can be rendered or not.

## Evidence
readitems

### CODE REVIEW

**Comment by onfranciis** [comment]
Screenshot from 2023-08-23 23-59-58

It handled the white screen but generated a new problem, payment invoices are not showing accurate data

**Review by salahlalami — CHANGES_REQUESTED** [review]
@Ando22  it doesn't show the payment amount, 
please **duplicate readItem component inside PaymentModule** , and try to fix issue.

Payment shoudn't use same module as invoice/quote

**Comment by Ando22** [comment]
> 

hi @onfranciis updated the changes, you may check again 🙏

**Review by adeojoemmanuel — APPROVED** [review]

**Review by polymahh — APPROVED** [review]
LGTM 👍  tested locally

**Review by salahlalami — CHANGES_REQUESTED** [review]
@Ando22 could you duplicate this frontend/src/components/ErpPanel/ReadItem.jsx inside PaymentModule ,
we want to keep module payment isoleted from other module

**Comment by Ando22** [comment]
> @Ando22 could you duplicate this frontend/src/components/ErpPanel/ReadItem.jsx inside PaymentModule , we want to keep module payment isoleted from other module

@salahlalami  I did, I create this `frontend/src/modules/PaymentModule/PaymentInvoiceItem.jsx` which is a copied of `frontend/src/components/ErpPanel/ReadItem.jsx `

**Comment by salahlalami** [comment]
@Ando22 ok , thanks

**Review by Fernando7181 — APPROVED** [review]

**Pull request merged**
