### PR TITLE
584_bug_fix_by Sandeep

### PR DESCRIPTION
**Pull request by sandeeppatel2001**
## Checklist

- [x] I have tested these changes
- [x] I have updated the relevant documentation
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the codebase
- [x] My changes generate no new warnings or errors
- [x] The title of my pull request is clear and descriptive

### CODE REVIEW

**Comment by salahlalami** [comment]
@sandeeppatel2001 this will break all create methods core ,
you need to ovveride create methode just for client controller

**Review by salahlalami — CHANGES_REQUESTED** [review]
please revert this file , and override only client controller create method

**Comment by Treuweille** [comment]
How are you, what you needed

**Comment by sandeeppatel2001** [comment]
## on frontend side---------------------------------------------------
## after clicking submit button ,  function will  call in following order -------->
frontend\src\components\CreateForm\index.jsx ------file
dispatch(crud.create({ entity, jsonData: trimmedValues, withUpload }));     
                                               |
                                               |
frontend\src\redux\crud\actions.js------------file
create:
    ({ entity, jsonData, withUpload = false }) =>
    async (dispatch) => {
      dispatch({
        type: actionTypes.REQUEST_LOADING,
        keyState: 'create',
        payload: null,
      });
      let data = null;
      if (withUpload) {
        data = await request.createAndUpload({ entity, jsonData });
      } else {
        data = await request.create({ entity, jsonData });     // here this will call      //    calling this  for new customer creation
      }   
                                                        |
                                                        |
frontend\src\request\request.js --------------file
const request = {
  create: async ({ entity, jsonData }) => {
    try {
      const response = await axios.post(entity + '/create', jsonData);   //////  sending to backend for "/creaate" directly 
      successHandler(response, {
        notifyOnSuccess: true,
        notifyOnFailed: true,
      });
      return response.data;
    } catch (error) {
      return errorHandler(error);
    }
  },
  
                                                                          |
                                                                          |

##  -----------------------------------------------backend side -----------------------------------------------------------
backend\routes\appRoutes\appApi.js -----------file
const clientController = require('@/controllers/appControllers/clientController');
router.route('/client/create').post(hasPermission('create'), catchErrors(clientController.create));                                   

                                                                               |
backend\controllers\middlewaresControllers\createCRUDController\index.js----------file
const createCRUDController = (modelName) => {
  const Model = mongoose.model(modelName);
  let crudMethods = {};

  crudMethods.create = async (req, res) => {
    create(Model, req, res);
  };
  crudMethods.read = async (req, res) => {
    read(Model, req, res);
  };
  
                                                                                      |
                                                                                      |
backend\controllers\middlewaresControllers\createCRUDController\create.js----------file
const create = async (Model, req, res) => {
  try {
    // Creating a new document in the collection

    const result = await new Model(req.body).save();

    // Returning successfull response
    return res.status(200).json({
      success: true,
      result,
      message: 'Successfully Created the document in Model ',
    });
  } catch (error) {

  where should i inter
  
  ----------------------------------------------------------------------------------------------------------------

I hope this message finds you well. I'm facing a dilemma regarding where to intercept these requests to minimize unnecessary backend calls.

If I make changes at the frontend, the current implementation involves sending two separate requests—one for checking updates and another for creating. This, however, increases the overall processing time. On the other hand, modifying the backend router to redirect create requests through an update check first seems like a viable solution.

I think here=router.route('/client/create').post(hasPermission('create'), catchErrors(clientController.create));      instead of  calling create first we should check for update 
The current update function in the backend is designed to work with _id (Model.findOneAndUpdate({ _id: req.params.id, removed: false }, req.body, {}), but in my case, updates are identified by the company name. Do you think it would be appropriate to create a separate function for updating based on the company name, or is there a more elegant solution?

I'm eager to hear your thoughts and experiences with similar challenges. Your insights will be invaluable in shaping the best approach for this implementation.

Thank you for your time and expertise.

**Pull request closed without merging**
