### PR TITLE
Dockerfile added

### PR DESCRIPTION
**Pull request by Rajdeep1311**
Please check  the contents of the file.

### CODE REVIEW

**Comment by salahlalami** [comment]
@Rajdeep1311 please this can run both backend and frontend

**Comment by Rajdeep1311** [comment]
Yeah

**Comment by Rajdeep1311** [comment]
from this the docker image can be built and then we can run it on container on the port given

**Comment by Rajdeep1311** [comment]
Still let me check once

**Comment by anonymous4561** [comment]
@salahlalami @polymahh is there any issue help wanted where i can work on?

**Comment by polymahh** [comment]
this will be closed in favor of this PR https://github.com/idurar/idurar-erp-crm/pull/286

**Pull request closed without merging**
