### PR TITLE
refactor: use calculate helper method

### LINKED ISSUE #279: API : Replace all Invoice Quote payment  Calculation with Calculate Helper Method
Replace all  Calculation with Calculate Helper Method : 

* paymentInvoiceController
* invoiceController
* quoteController

Example : 

Convert 

```javascript
const changedAmount = currentAmount - previousAmount;
```

to

```javascript
const { calculate } = require('@/helpers');

const changedAmount = calculate.sub(currentAmount , previousAmount);
```

### PR DESCRIPTION
**Pull request by vinaybadgujar102**
resolves #279 @salahlalami @polymahh

### CODE REVIEW

**Comment by polymahh** [comment]
I am sorry again @vinaybadgujar102 😄 
 there is already an approved PR for this https://github.com/idurar/idurar-erp-crm/pull/420
 pls always check the PRs if somebody already worked on it to avoid wasting ur time 
 i think this is clear in the contributing.md file

**Comment by salahlalami** [comment]
@polymahh  this is one is for backend calculation , the other is for frontend 
thank you @vinaybadgujar102

**Comment by polymahh** [comment]
sorry @vinaybadgujar102 i did not see the files 😄

**Review by salahlalami — APPROVED** [review]
Thank you again @vinaybadgujar102

**Review by polymahh — APPROVED** [review]

**Pull request merged**
