### PR TITLE
Feature/create new url navigation for invoice 263 v2

### PR DESCRIPTION
**Pull request by onfranciis**
Screenshot from 2023-08-29 01-18-15
Screenshot from 2023-08-29 01-18-03
Screenshot from 2023-08-29 01-17-45
Screenshot from 2023-08-29 01-17-34

I added the create, read and update sub routes for invoice and quote. This addresses issue #263 and is a successor of PR #349

### CODE REVIEW

**Review by adeojoemmanuel — APPROVED** [review]

**Review by adeojoemmanuel — CHANGES_REQUESTED** [review]
resolve conflict

**Comment by polymahh** [comment]
@onfranciis the new url navigation is working great and tested locally
but you have to update your branch to latest dev

**Comment by onfranciis** [comment]
@adeojoemmanuel and @polymahh the changes have been made.

**Review by salahlalami — APPROVED** [review]

**Review by polymahh — APPROVED** [review]
LGTM 👍

**Comment by salahlalami** [comment]
Hi @onfranciis please merge this before start refactoring

**Pull request merged**
