### PR TITLE
issue #213 Employee details still remains open even after delete Success

### PR DESCRIPTION
**Pull request by LOGESH-B**
The side panel is now closed after the delete request is done

### CODE REVIEW

**Comment by salahlalami** [comment]
@onfranciis please test it before approve it

**Review by polymahh — CHANGES_REQUESTED** [review]
this is working but i think it is better to use this combination 

readBox.close();
panel.close();
navMenu.open();

the navigation should open back up and remove collapsedBox.close();
also remove package-lock files no need for them here

**Comment by polymahh** [comment]
@LOGESH-B i think you missed this one navMenu.open() 😄
was that codesee file added by github ?

**Comment by LOGESH-B** [comment]
> @LOGESH-B i think you missed this one navMenu.open() 😄 was that codesee file added by github ?

Hii @polymahh 
Yes.I don't know where codesee file comes from

```
    readBox.close();
    panel.close();
    navMenu.collapse();
    navMenu.open();
```

    I don't see any visible changes after navMenu.open()🥴

**Review by polymahh — APPROVED** [review]
@LOGESH-B true i just tested it , it's working

**Review by Fernando7181 — APPROVED** [review]

**Review by onfranciis — APPROVED** [review]
Tested

**Pull request merged**
