### PR TITLE
Added Swahili Langauage

### PR DESCRIPTION
**Pull request by gsnilloC**
## Description

Please provide a brief description of the changes or additions made in this pull request.

Added a sw_ke.js file which holds the correct Swahili translations.

## Related Issues

If this pull request is related to any issue(s), please list them here.

## Steps to Test

1. Created sw_ke.js file and added translations
2.  Deleted `disabled: true` and (coming soon)
3. Moved Swahili to the group of enabled langauges

## Screenshots (if applicable)

If your changes include visual updates, it would be helpful to provide screenshots of the before and after.

## Checklist

- [ ] I have tested these changes
- [ ] I have updated the relevant documentation
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the codebase
- [ ] My changes generate no new warnings or errors
- [ ] The title of my pull request is clear and descriptive

### CODE REVIEW

**Comment by salahlalami** [comment]
@gsnilloC  please check issue description ,there some files need to be modified

**Comment by gsnilloC** [comment]
> @gsnilloC please check issue description ,there some files need to be modified

I was able to modify the files needed.

**Comment by salahlalami** [comment]
@gsnilloC 
there is something missed , test it first and make it work , and add screenshot of swahli language

**Comment by salahlalami** [comment]
@gsnilloC antd doesn't support swahili at moment , i will close this pr

**Pull request closed without merging**
