### PR TITLE
PR: Removed trailing space from '.prettierignore'

### PR DESCRIPTION
**Pull request by sweetapplepumpkinpie**
@idurar There is a problem to clone this repository. The reason is that `.prettierignore` files have trailing white space in their name.  So I fixed it and opened this PR.

### CODE REVIEW

**Comment by idurar** [comment]
@sweetapplepumpkinpie did you apply for idurar job ?

**Comment by sweetapplepumpkinpie** [comment]
> @sweetapplepumpkinpie did you apply for idurar job ?

yeah,

**Comment by idurar** [comment]
@sweetapplepumpkinpie what's your name ? i couldn't found you ?

**Comment by sweetapplepumpkinpie** [comment]
> @sweetapplepumpkinpie what's your name ? i couldn't found you ?

I'm Tony Wang

**Comment by idurar** [comment]
@sweetapplepumpkinpie i couldn't find you , send me please your linkedin profile or resume to lalami.sdn@gmail.com

**Comment by sweetapplepumpkinpie** [comment]
> @sweetapplepumpkinpie i couldn't find you , send me please your linkedin profile or resume to [lalami.sdn@gmail.com](mailto:lalami.sdn@gmail.com)

just sent

**Pull request merged**
