### PR TITLE
fix: resolved login error

### PR DESCRIPTION
**Pull request by adeojoemmanuel**
updated login and logout function by updating $inc to $set as the $inc operator is specifically designed to work with numeric values

### CODE REVIEW

**Review by polymahh — APPROVED** [review]
tested locally, login is working 👍 
@adeojoemmanuel can you remove the space in authJwtController.js file name

**Review by salahlalami — CHANGES_REQUESTED** [review]
pls remove the space in authJwtController.js file name

**Comment by adeojoemmanuel** [comment]
alright i would, i think we should also add a task to run lint using pre-commit hook so to always remove spaces

**Review by salahlalami — APPROVED** [review]

**Comment by salahlalami** [comment]
@adeojoemmanuel thanks , pr approved

**Pull request merged**
