### PR TITLE
fix:corrected issue #306:the menu is not highlighted

### PR DESCRIPTION
**Pull request by ashmeetsmonga**
Corrected the issue #306  where the menu is not being highlighted if the page is visited by changing the url

https://github.com/idurar/idurar-erp-crm/assets/56465357/7f1a877f-ea71-4a12-b12d-f909591d470a

### CODE REVIEW

**Review by polymahh — CHANGES_REQUESTED** [review]
i wanted to remove yarn.lock and package-lock.jason ,  but i did a mistake now it will be removed from the project 👎 
can you fix it and remove packaje.json and yarn.lock from the PR we only need the navigation file

**Comment by ashmeetsmonga** [comment]
Corrected @polymahh. I don't know why now it is showing change in yarn.lock even though the same line is being shown as removed and added.

**Comment by polymahh** [comment]
@ashmeetsmonga sorry i think my commit is what made it stick ... if there is no way to fix it just close this PR and create a new branch from dev and copy your code it is going to be easier... i already tested your code

**Comment by ashmeetsmonga** [comment]
@polymahh new pr #316  raised. Closing this one.

**Pull request closed without merging**
