### PR TITLE
Issues/fix css style for responsive dashboard

### PR DESCRIPTION
**Pull request by brunovjk**
This pull request addresses the #332 Issue.
Adjusted some  CSS settings on Dashboard\Analytics... to make the dashboard responsive at all widths.

Still need to deal with `number gets longer it is going off border`
263246885-b2ccc257-5fa6-4e15-a50e-687cf628aea6

What would be a better approach? Does it break the number into two or more columns, or into specific `width` using column instead of row?

### CODE REVIEW

**Comment by polymahh** [comment]
hello @brunovjk allow me to add some changes to This PR

**Comment by polymahh** [comment]
@brunovjk can you pls pull the changes and see if everything is good and give me a screenshot

**Comment by brunovjk** [comment]
Like this @polymahh?
elipses_and_tooltip
For me everything looks good!

**Review by polymahh — APPROVED** [review]
i just want to make sure i didn't ruin ur work

**Review by salahlalami — APPROVED** [review]

**Comment by brunovjk** [comment]
Hi @polymahh, not ruined at all. I liked what you did.

**Review by Ando22 — APPROVED** [review]

**Pull request merged**
