### PR TITLE
Features/implement calculate helper method

### PR DESCRIPTION
**Pull request by arpitnakrani**
Implemented calculate helper method for paymentInvoiceController.

### CODE REVIEW

**Review by polymahh — CHANGES_REQUESTED** [review]
hello @arpitnakrani thank you for your help
branch from `dev` (make sure it is updated ) not from master
the PR should only have changes related to the issue
do not update dependencies

**Comment by arpitnakrani** [comment]
> hello @arpitnakrani thank you for your help branch from `dev` (make sure it is updated ) not from master the PR should only have changes related to the issue do not update dependencies

okay can you help me with  setting up FE , as i tried to but it was giving error (attached ss below) , thank you.
image

**Comment by anonymous4561** [comment]
do npm run start

**Comment by arpitnakrani** [comment]
> do npm run start
still same error @anonymous4561 
image

**Comment by polymahh** [comment]
try removing the node mudles folder and install again
`cd frontend`
`rm -rf node_modules`
`npm install`

**Comment by anonymous4561** [comment]
> @arpitnakrani try removing the node mudles folder and install again `cd frontend` `rm -rf node_modules` `npm install`

S this Works

**Comment by arpitnakrani** [comment]
can you llok into new pr i have created for dev branch @polymahh , let me know if its correct then i can implement it for also other 2 controller.

**Comment by arpitnakrani** [comment]
For FE still facing craco start error @anonymous4561 @polymahh  , BE is running fine for me

**Comment by polymahh** [comment]
@arpitnakrani if you can stat from the beginning
and follow the getting started guide 
I am going to close this PR 
if you still have issues create a new issue and give us as much details as possible and follow the contributing guide

**Comment by arpitnakrani** [comment]
okay @polymahh will do that

**Pull request closed without merging**
