### PR TITLE
 fix #328 Update quote when invoice is deleted

### LINKED ISSUE #328: [FIX] Update quote when invoice is deleted
Screenshot from 2023-08-21 22-35-46

When an invoice that was generated from a quote is deleted, the quote is still marked as converted=true and is preventing the quote from been converted again

### PR DESCRIPTION
**Pull request by Nam1001**
fix #328 

problem 
The Delete button was not working properly.When the user was click on the delete button the quote was not getting deleted

How to produce
1.Go to quote section.
2. Create a new quote by fill all the details.
3. Now save the quote.
4. Now click on the delete button.

### CODE REVIEW

**Comment by Nam1001** [comment]
@polymahh please review the pr

**Review by salahlalami — CHANGES_REQUESTED** [review]
This issue bug was caused since we add new features : https://github.com/idurar/idurar-erp-crm/pull/327

**Comment by Nam1001** [comment]
@salahlalami i am not getting you this there is any issue with the pr??

**Comment by onfranciis** [comment]
@Nam1001 seems like this branch was created from an outdated dev branch. Please switch your upstream to dev, run a git pull, make your changes, commit, push and we can review them.

**Pull request closed without merging**
