### PR TITLE
Fix  : Resolve drawer wrapper style for side-nav in mobile view

### PR DESCRIPTION
**Pull request by raphael3213**
## Description

Added styling fot the Ant Design drawer
- Enable transparency
- Remove box shadow
- Increased the width for better transition fluidity
- Removed the css class as it was not affecting the component

## Related Issues

https://github.com/idurar/idurar-erp-crm/issues/854

## Steps to Test

1. Visit Home page
2. Login as admin
3. Shrink the screen size to minimum or use Dev tools to view the app in mobile
4. Open the side nav to observe the white background behind the navbar.

Provide steps on how to test the changes introduced in this pull request.

## Screenshots (if applicable)

Before :  
idura-side-nav-mobile-view-current

After : 

idura-side-nav-mobile-view-fixed

## Checklist

- [X] I have tested these changes
- [ ] I have updated the relevant documentation
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the codebase
- [X] My changes generate no new warnings or errors
- [X] The title of my pull request is clear and descriptive

### CODE REVIEW

**Review by salahlalami — CHANGES_REQUESTED** [review]
@raphael3213 please to remove margin in left and top , and also remove radius corner (only in mobile view)

**Comment by raphael3213** [comment]
Will do.

**Comment by raphael3213** [comment]
@salahlalami Would you like the shadow and left and top margin removed for side nav , on larger devices too ? The css is applied on the Sider component, so if I remove them, it will also remove the margin for the side bar for larger screens.




This is the result screen for mobile : 

idura-side-nav-mobile-padding-removed

**Comment by raphael3213** [comment]
@salahlalami Made the changes to ensure no margin left , top and radius for the side nav on **mobile view only**. This will only apply when rendering the MobileSidebar component.

idura-side-nav-mobile-padding-removed

**Pull request merged**
