### PR TITLE
empty state of previews handled

### PR DESCRIPTION
**Pull request by rkmdCodes**
This PR is closing issue #372 

image

### CODE REVIEW

**Comment by salahlalami** [comment]
@rkmdCodes could you pls include a video of result here

**Comment by rkmdCodes** [comment]
hi @salahlalami  sir
This is the screen recording of result

https://github.com/idurar/idurar-erp-crm/assets/113243168/a17c9ee8-276c-4f71-baf0-bfb45b9e731d

**Comment by Ando22** [comment]
Hi @rkmdCodes Thank you for the PR! I see that your branch is not updated base on `dev` branch. our analytic component is moved from `/components/Dashboard/...` to `/modules/DashboardModule/components/...`

**Comment by rkmdCodes** [comment]
hi @salahlalami  @Ando22 @polymahh  , 

Thanks for the review.
I have updated the branch to latest dev branch,
The issue is now resolved

https://github.com/idurar/idurar-erp-crm/assets/113243168/d2c2371d-3233-4338-8ac3-a257b9a5d9e4

**Comment by polymahh** [comment]
this PR will be closed in favor of this solution https://github.com/idurar/idurar-erp-crm/pull/393

**Pull request closed without merging**
