### PR TITLE
[Feat][FrontEnd] Navigation on mobile device

### PR DESCRIPTION
**Pull request by quan-nh2**
# What's changed:
- [x] Make navigation close by default on mobile device size.
- [x] Hide the Content part when navigation is open on mobile device size.
- [x] Close navigation when we click on content on mobile device size.
- [x] Add CSS rules to Navigation on mobile device size :
```code
  @media (max-width: 768px) {
    overflow-y: scroll;
  }
```

# Related issues: #288 
[Navigation on Mobile phone](https://github.com/idurar/idurar-erp-crm/issues/288)

@salahlalami Let me know if you want to change or update something. Thanks!

### CODE REVIEW

**Comment by salahlalami** [comment]
@polymahh check this PR , and test it please localy

**Comment by salahlalami** [comment]
@quan-nh2 could you please add video record of result

**Comment by quan-nh2** [comment]
Sure, below is the video record of result:
- Mobile-only:

https://github.com/idurar/idurar-erp-crm/assets/22234293/9441bb47-9738-4883-832b-ba598347a614



- Responsive from desktop to mobile:


https://github.com/idurar/idurar-erp-crm/assets/22234293/cf383206-e69a-4683-9c61-5996a47f67cb

**Comment by polymahh** [comment]
thank you @quan-nh2 you've given us the opportunity to test this idea, but it does not seem like a good user experience

**Comment by quan-nh2** [comment]
> thank you @quan-nh2 you've given us the opportunity to test this idea, but it does not seem like a good user experience

Yep, because it seems we do not have a design version for mobile, maybe we need one 🎨

**Comment by polymahh** [comment]
@quan-nh2  this is the solution we will be working with for now https://github.com/idurar/idurar-erp-crm/pull/294

**Pull request closed without merging**
