### PR TITLE
register_fx

### PR DESCRIPTION
**Pull request by collinskoech11**
Tried to implement register  functionality
Email confirmation and super admin approval would be a next good feature

### CODE REVIEW

**Comment by collinskoech11** [comment]
@salahlalami kindly review

**Review by collinskoech11 — COMMENTED** [review]
_

**Comment by polymahh** [comment]
this will be closed as we already added register page

**Comment by Atuldubey98** [comment]
Can some explain the functionality of the register page when user clicks on register button? I need to work on the backend for the register route. In case register fx is not done for backend. Please let me know the functionality to provide?

**Comment by collinskoech11** [comment]
@Atuldubey98 .This feature was already implemented,  thus the reason for this PR being closed instead of being merged.

**Pull request closed without merging**
