### PR TITLE
Feat: added the dropdown function to notificaton icon

### PR DESCRIPTION
**Pull request by sidgaikwad**
fixes: #339 
1) created a notification dropdown 
2) It has a delete button to delete the notifications
image
image

### CODE REVIEW

**Comment by salahlalami** [comment]
Tahnk you @sidgaikwad create separate folder component/notification

**Comment by polymahh** [comment]
thank you @sidgaikwad also can you post some screenshots

**Comment by sidgaikwad** [comment]
added some  screenshots

**Comment by sidgaikwad** [comment]
@salahlalami created the Components/Notification folder in the components section.

**Comment by polymahh** [comment]
just in case you didn't , make sure the drop down have a max-height and it should scroll when there is a lot of notifications

**Comment by sidgaikwad** [comment]
@polymahh do you want a custom scrollbar or the regular one that the webapp is using
image

**Comment by polymahh** [comment]
yh a custom one sounds great
i was thinking we could make it with some shades of these blue colors
image
and it should be thin just like the vertical blue line
@sidgaikwad sorry we don't have a design for this 😄

**Comment by sidgaikwad** [comment]
image
@polymahh will this color do the job

**Comment by polymahh** [comment]
use this color #1B98F5
width:4px or 3px
height: 60px

**Comment by sidgaikwad** [comment]
image
image


@polymahh ok done

**Comment by polymahh** [comment]
yh just commit it to the same branch

**Comment by sidgaikwad** [comment]
@polymahh done !!

**Review by polymahh — APPROVED** [review]
LGTM 👍

**Review by salahlalami — APPROVED** [review]
Nice 👍

**Pull request merged**
