### PR TITLE
Api customer analytics

### PR DESCRIPTION
**Pull request by anonymous4561**
### Context

- I have created 10 Dummy Customer Data where four user was Active  last 30 days According do their Login   and Five User where created this Month 
- Active Customer's for Now I think we would fetch from their Last login  Please I need Help over this

### API Structure:

- Endpoint: `api/customer/read`
- Method: `GET`

### Response

> {"success":true,"result":{"perThisMonth":50,"perThirtyDaysCustomerLogin":40},"message":"success"}

edurar

That Data has been fetched from that above API

i would like make one more commit to remove // commands  from setup.js which holds dummy data for customer and will remove Customer Model aswell once the review is made

### CODE REVIEW

**Comment by anonymous4561** [comment]
@salahlalami Please check the contents of the file.

**Comment by polymahh** [comment]
I couldn't run this branch

image

**Comment by anonymous4561** [comment]
@polymahh thanks for reviewing it my bad i forget to do null handling what will customer are not there in database ?
Thanks for running the code and please check again

**Review by polymahh — APPROVED** [review]
tested locally it is working 

image

**Comment by anonymous4561** [comment]
@polymahh  Thank u for approving it

**Comment by Ando22** [comment]
Hi @anonymous4561 

Thank you for the Pull Request and the effort in enhancing the dashboard. Just a quick thought – I think instead of creating new tables, you might want to consider pulling data for the reports directly from the existing `client` table. you can see from the 'Customer' menu on the Dashboard. it refers to `client` table. 

here I create a [Draft Pull Request](https://github.com/idurar/idurar-erp-crm/pull/297) for this feature. feel free to comment or add more

cc: @salahlalami

**Comment by anonymous4561** [comment]
Oh yeah u r right.

**Pull request closed without merging**
