### PR TITLE
fix: Handle empty state in PreviewCard with default statistics

### PR DESCRIPTION
**Pull request by brunovjk**
This pull request directly addresses issue #372

Approach involved using default values for display when the backend returns empty data.
I think this approach aligns well, considering other components on the same dashboard use 0 as default values.

### CODE REVIEW

**Review by Ando22 — APPROVED** [review]

**Comment by polymahh** [comment]
hello @brunovjk thank you for your help , i just tested it it's working great 
can you please check for each one and render the empty state so we dont get that empty space 
image

**Comment by Ando22** [comment]
> hello @brunovjk thank you for your help , i just tested it it's working great can you please check for each one and render the empty state so we dont get that empty space image

Hi @polymahh I agree with this. I'm open for frontend solutions for this, but I already handle on the backend side on this [PR](https://github.com/idurar/idurar-erp-crm/pull/414)

**Comment by brunovjk** [comment]
@polymahh what do you think? (commit)[https://github.com/idurar/idurar-erp-crm/pull/393/commits/5cbcb0365511e365530559e47e773bc363de182a]

**Comment by polymahh** [comment]
image
@brunovjk looks great 👍

**Review by polymahh — APPROVED** [review]

**Review by salahlalami — APPROVED** [review]

**Pull request merged**
