### PR TITLE
datatable title fix and title fixes

### PR DESCRIPTION
**Pull request by npiyush97**
uppercased title and fixed issue, data table title called with the wrong variable name.

### CODE REVIEW

**Review by npiyush97 — COMMENTED** [review]
for automated pr review

**Review by salahlalami — APPROVED** [review]
Thanks 👍

**Review by Ando22 — APPROVED** [review]

**Comment by npiyush97** [comment]
@salahlalami why is pr still not merged?

**Comment by salahlalami** [comment]
@npiyush97 thank , check other issues if you want continue contributing to IDURAR

**Pull request merged**
