### PR TITLE
Feature/Added scrollbar on the notifications dropdown

### PR DESCRIPTION
**Pull request by sangwan14**
The notifications on the bottom weren't visible so I added a scrollbar.

https://github.com/idurar/idurar-erp-crm/assets/68826136/11bd4fc6-f1fa-40f1-9f37-2fef329f1ff0

### CODE REVIEW

**Comment by salahlalami** [comment]
@sangwan14 record video on result

**Comment by sangwan14** [comment]
> @sangwan14 pls record video on result

done pls check

**Comment by salahlalami** [comment]
I think this @sangwan14  already fixed by @polymahh

**Comment by salahlalami** [comment]
@sangwan14 here pr https://github.com/idurar/idurar-erp-crm/pull/379

**Pull request closed without merging**
